-- Phase 7.2 — Additive Reconciliation Migration
-- Generated by Directive 49.2 (design-only → execution)
-- PURELY ADDITIVE: CREATE TABLE + CREATE INDEX + ALTER ADD COLUMN
-- 0 DROP TABLE, 0 DROP COLUMN, 0 destructive recreation
-- Reconciles migration history with schema.prisma (43 missing + 5 divergent + HeroConfig)

-- ═══ Category A: 43 missing tables (additive CREATE TABLE) ═══
-- AIAgent
CREATE TABLE "AIAgent" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "key" TEXT NOT NULL,
    "nameFa" TEXT NOT NULL,
    "nameEn" TEXT,
    "description" TEXT,
    "taskType" TEXT NOT NULL,
    "config" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "lastRunAt" DATETIME,
    "lastStatus" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
CREATE UNIQUE INDEX "AIAgent_key_key" ON "AIAgent"("key");

-- AIBudget
CREATE TABLE "AIBudget" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT 'main',
    "dailyLimitUsd" REAL NOT NULL DEFAULT 10.0,
    "monthlyLimitUsd" REAL NOT NULL DEFAULT 200.0,
    "dailySpendUsd" REAL NOT NULL DEFAULT 0.0,
    "monthlySpendUsd" REAL NOT NULL DEFAULT 0.0,
    "dailyResetAt" DATETIME,
    "monthlyResetAt" DATETIME,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- AITaskPolicy
CREATE TABLE "AITaskPolicy" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "taskType" TEXT NOT NULL,
    "allowedRoles" TEXT NOT NULL,
    "hourlyLimit" INTEGER NOT NULL DEFAULT 30,
    "dailyLimit" INTEGER NOT NULL DEFAULT 100,
    "maxInputChars" INTEGER NOT NULL DEFAULT 5000,
    "maxOutputTokens" INTEGER NOT NULL DEFAULT 2000,
    "model" TEXT NOT NULL DEFAULT 'default',
    "timeoutMs" INTEGER NOT NULL DEFAULT 30000,
    "costCeilingUsd" REAL NOT NULL DEFAULT 0.05,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
CREATE UNIQUE INDEX "AITaskPolicy_taskType_key" ON "AITaskPolicy"("taskType");

-- AdminNavigationGroup
CREATE TABLE "AdminNavigationGroup" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "key" TEXT NOT NULL,
    "titleFa" TEXT NOT NULL,
    "titleEn" TEXT,
    "icon" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
CREATE UNIQUE INDEX "AdminNavigationGroup_key_key" ON "AdminNavigationGroup"("key");

-- AdminNavigationItem
CREATE TABLE "AdminNavigationItem" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "groupId" TEXT,
    "key" TEXT NOT NULL,
    "titleFa" TEXT NOT NULL,
    "titleEn" TEXT,
    "href" TEXT NOT NULL,
    "icon" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "permissionKey" TEXT,
    "featureFlag" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "openInNewTab" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "AdminNavigationItem_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "AdminNavigationGroup" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "AdminNavigationItem_active_idx" ON "AdminNavigationItem"("active");
CREATE INDEX "AdminNavigationItem_groupId_idx" ON "AdminNavigationItem"("groupId");
CREATE UNIQUE INDEX "AdminNavigationItem_key_key" ON "AdminNavigationItem"("key");

-- AdminPreference
CREATE TABLE "AdminPreference" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "theme" TEXT NOT NULL DEFAULT 'system',
    "density" TEXT NOT NULL DEFAULT 'comfortable',
    "locale" TEXT NOT NULL DEFAULT 'fa',
    "timezone" TEXT NOT NULL DEFAULT 'Asia/Tehran',
    "sidebarCollapsed" BOOLEAN NOT NULL DEFAULT false,
    "pinnedItems" JSONB,
    "hiddenItems" JSONB,
    "dashboardLayout" JSONB,
    "defaultPageSize" INTEGER NOT NULL DEFAULT 25,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
CREATE UNIQUE INDEX "AdminPreference_userId_key" ON "AdminPreference"("userId");

-- AdminSavedView
CREATE TABLE "AdminSavedView" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "resourceKey" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "scope" TEXT NOT NULL DEFAULT 'PERSONAL',
    "config" JSONB NOT NULL,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
CREATE INDEX "AdminSavedView_resourceKey_scope_idx" ON "AdminSavedView"("resourceKey", "scope");
CREATE INDEX "AdminSavedView_userId_resourceKey_idx" ON "AdminSavedView"("userId", "resourceKey");

-- AnalyticsEvent
CREATE TABLE "AnalyticsEvent" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "eventType" TEXT NOT NULL,
    "userId" TEXT,
    "listingId" TEXT,
    "categoryId" TEXT,
    "brandId" TEXT,
    "query" TEXT,
    "page" TEXT,
    "referrer" TEXT,
    "ip" TEXT,
    "userAgent" TEXT,
    "metadata" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "AnalyticsEvent_createdAt_idx" ON "AnalyticsEvent"("createdAt");
CREATE INDEX "AnalyticsEvent_eventType_idx" ON "AnalyticsEvent"("eventType");
CREATE INDEX "AnalyticsEvent_listingId_idx" ON "AnalyticsEvent"("listingId");
CREATE INDEX "AnalyticsEvent_userId_idx" ON "AnalyticsEvent"("userId");

-- Attachment
CREATE TABLE "Attachment" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "productId" TEXT,
    "attachmentType" TEXT,
    "capacity" TEXT,
    "condition" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Attachment_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX "Attachment_productId_idx" ON "Attachment"("productId");

-- CompanyBranch
CREATE TABLE "CompanyBranch" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "companyId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT,
    "cityId" TEXT,
    "phone" TEXT,
    "isHeadquarters" BOOLEAN NOT NULL DEFAULT false,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CompanyBranch_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CompanyBranch_cityId_fkey" FOREIGN KEY ("cityId") REFERENCES "City" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX "CompanyBranch_companyId_idx" ON "CompanyBranch"("companyId");

-- CompanyDocument
CREATE TABLE "CompanyDocument" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "companyId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "verifiedBy" TEXT,
    "verifiedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CompanyDocument_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "CompanyDocument_companyId_idx" ON "CompanyDocument"("companyId");

-- CompanyPartner
CREATE TABLE "CompanyPartner" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "companyId" TEXT NOT NULL,
    "partnerId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "requestedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "acceptedAt" DATETIME,
    "notes" TEXT,
    CONSTRAINT "CompanyPartner_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CompanyPartner_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "Company" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "CompanyPartner_companyId_idx" ON "CompanyPartner"("companyId");
CREATE UNIQUE INDEX "CompanyPartner_companyId_partnerId_key" ON "CompanyPartner"("companyId", "partnerId");
CREATE INDEX "CompanyPartner_partnerId_idx" ON "CompanyPartner"("partnerId");
CREATE INDEX "CompanyPartner_status_idx" ON "CompanyPartner"("status");

-- CompanyVerification
CREATE TABLE "CompanyVerification" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "companyId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "verificationType" TEXT NOT NULL DEFAULT 'BUSINESS',
    "submittedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reviewedAt" DATETIME,
    "reviewedBy" TEXT,
    "notes" TEXT,
    "evidence" TEXT,
    "expiresAt" DATETIME,
    "revokedAt" DATETIME,
    "revokedBy" TEXT,
    "revokeReason" TEXT,
    CONSTRAINT "CompanyVerification_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "CompanyVerification_companyId_idx" ON "CompanyVerification"("companyId");
CREATE INDEX "CompanyVerification_status_idx" ON "CompanyVerification"("status");

-- ComparisonItem
CREATE TABLE "ComparisonItem" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "sessionId" TEXT NOT NULL,
    "listingId" TEXT,
    "productId" TEXT,
    "brandId" TEXT,
    "modelId" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "ComparisonItem_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "ComparisonSession" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ComparisonItem_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "Listing" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX "ComparisonItem_sessionId_idx" ON "ComparisonItem"("sessionId");

-- ComparisonSession
CREATE TABLE "ComparisonSession" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "name" TEXT,
    "shareToken" TEXT,
    "shareExpiresAt" DATETIME,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "aiSummary" TEXT,
    "aiSummaryAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
CREATE UNIQUE INDEX "ComparisonSession_shareToken_key" ON "ComparisonSession"("shareToken");

-- CompatibilityEdge
CREATE TABLE "CompatibilityEdge" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "sourceEntityType" TEXT NOT NULL,
    "sourceEntityId" TEXT NOT NULL,
    "targetEntityType" TEXT NOT NULL,
    "targetEntityId" TEXT NOT NULL,
    "relationType" TEXT NOT NULL,
    "confidence" REAL,
    "source" TEXT,
    "verified" BOOLEAN NOT NULL DEFAULT false,
    "verifiedBy" TEXT,
    "verifiedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "CompatibilityEdge_sourceEntityType_sourceEntityId_idx" ON "CompatibilityEdge"("sourceEntityType", "sourceEntityId");
CREATE UNIQUE INDEX "CompatibilityEdge_sourceEntityType_sourceEntityId_targetEntityType_targetEntityId_relationType_key" ON "CompatibilityEdge"("sourceEntityType", "sourceEntityId", "targetEntityType", "targetEntityId", "relationType");
CREATE INDEX "CompatibilityEdge_targetEntityType_targetEntityId_idx" ON "CompatibilityEdge"("targetEntityType", "targetEntityId");

-- Conversation
CREATE TABLE "Conversation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "listingId" TEXT,
    "participant1Id" TEXT NOT NULL,
    "participant2Id" TEXT NOT NULL,
    "lastMessageAt" DATETIME,
    "lastMessagePreview" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Conversation_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "Listing" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Conversation_participant1Id_fkey" FOREIGN KEY ("participant1Id") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Conversation_participant2Id_fkey" FOREIGN KEY ("participant2Id") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "Conversation_lastMessageAt_idx" ON "Conversation"("lastMessageAt");
CREATE INDEX "Conversation_participant1Id_idx" ON "Conversation"("participant1Id");
CREATE UNIQUE INDEX "Conversation_participant1Id_participant2Id_listingId_key" ON "Conversation"("participant1Id", "participant2Id", "listingId");
CREATE INDEX "Conversation_participant2Id_idx" ON "Conversation"("participant2Id");

-- Deal
CREATE TABLE "Deal" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "dealNumber" TEXT NOT NULL,
    "sourceType" TEXT NOT NULL,
    "sourceId" TEXT NOT NULL,
    "buyerId" TEXT,
    "sellerId" TEXT,
    "listingId" TEXT,
    "agreedAmount" BIGINT,
    "currency" TEXT NOT NULL DEFAULT 'IRR',
    "transactionType" TEXT NOT NULL DEFAULT 'SALE',
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "agreedAt" DATETIME,
    "confirmedAt" DATETIME,
    "completedAt" DATETIME,
    "cancelledAt" DATETIME,
    "cancelReason" TEXT,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Deal_buyerId_fkey" FOREIGN KEY ("buyerId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Deal_sellerId_fkey" FOREIGN KEY ("sellerId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Deal_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "Listing" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX "Deal_buyerId_idx" ON "Deal"("buyerId");
CREATE UNIQUE INDEX "Deal_dealNumber_key" ON "Deal"("dealNumber");
CREATE INDEX "Deal_listingId_idx" ON "Deal"("listingId");
CREATE INDEX "Deal_sellerId_idx" ON "Deal"("sellerId");
CREATE INDEX "Deal_status_idx" ON "Deal"("status");

-- DealDocument
CREATE TABLE "DealDocument" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "dealRoomId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "uploadedBy" TEXT,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DealDocument_dealRoomId_fkey" FOREIGN KEY ("dealRoomId") REFERENCES "DealRoom" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "DealDocument_dealRoomId_idx" ON "DealDocument"("dealRoomId");

-- Dispute
CREATE TABLE "Dispute" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "dealId" TEXT,
    "orderId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'OPEN',
    "reason" TEXT NOT NULL,
    "description" TEXT,
    "evidence" TEXT,
    "openedBy" TEXT NOT NULL,
    "openedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolution" TEXT,
    "resolvedBy" TEXT,
    "resolvedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Dispute_dealId_fkey" FOREIGN KEY ("dealId") REFERENCES "Deal" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Dispute_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "Dispute_dealId_idx" ON "Dispute"("dealId");
CREATE INDEX "Dispute_orderId_idx" ON "Dispute"("orderId");
CREATE INDEX "Dispute_status_idx" ON "Dispute"("status");

-- DisputeEvidence
CREATE TABLE "DisputeEvidence" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "disputeId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "description" TEXT,
    "uploadedBy" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DisputeEvidence_disputeId_fkey" FOREIGN KEY ("disputeId") REFERENCES "Dispute" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "DisputeEvidence_disputeId_idx" ON "DisputeEvidence"("disputeId");

-- HomeCategoryConfig
CREATE TABLE "HomeCategoryConfig" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT 'main',
    "homeCategoryGeneration" INTEGER NOT NULL DEFAULT 1,
    "homeCategoryParentId" TEXT,
    "updatedAt" DATETIME NOT NULL
);

-- Inspection
CREATE TABLE "Inspection" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "listingId" TEXT NOT NULL,
    "dealRoomId" TEXT,
    "requestedBy" TEXT NOT NULL,
    "inspectorId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'REQUESTED',
    "scheduledDate" DATETIME,
    "completedAt" DATETIME,
    "checklist" TEXT,
    "score" REAL,
    "reportUrl" TEXT,
    "photos" TEXT,
    "notes" TEXT,
    "price" BIGINT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Inspection_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "Listing" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "Inspection_listingId_idx" ON "Inspection"("listingId");
CREATE INDEX "Inspection_status_idx" ON "Inspection"("status");

-- Machine
CREATE TABLE "Machine" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "productId" TEXT,
    "listingId" TEXT,
    "serialNumber" TEXT,
    "manufactureYear" INTEGER,
    "hours" INTEGER,
    "condition" TEXT,
    "ownershipHistory" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Machine_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Machine_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "Listing" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX "Machine_productId_idx" ON "Machine"("productId");

-- Message
CREATE TABLE "Message" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "conversationId" TEXT NOT NULL,
    "senderId" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "attachmentUrl" TEXT,
    "read" BOOLEAN NOT NULL DEFAULT false,
    "readAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Message_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Message_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "Message_conversationId_idx" ON "Message"("conversationId");
CREATE INDEX "Message_createdAt_idx" ON "Message"("createdAt");
CREATE INDEX "Message_senderId_idx" ON "Message"("senderId");

-- ModerationLog
CREATE TABLE "ModerationLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "listingId" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "reason" TEXT,
    "riskScore" REAL,
    "flaggedIssues" TEXT,
    "moderatorId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ModerationLog_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "Listing" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "ModerationLog_action_idx" ON "ModerationLog"("action");
CREATE INDEX "ModerationLog_listingId_idx" ON "ModerationLog"("listingId");

-- Opportunity
CREATE TABLE "Opportunity" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "type" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "score" REAL NOT NULL,
    "metadata" TEXT,
    "status" TEXT NOT NULL DEFAULT 'NEW',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "Opportunity_createdAt_idx" ON "Opportunity"("createdAt");
CREATE INDEX "Opportunity_type_status_idx" ON "Opportunity"("type", "status");

-- Order
CREATE TABLE "Order" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "orderNumber" TEXT NOT NULL,
    "dealId" TEXT NOT NULL,
    "titleSnapshot" TEXT NOT NULL,
    "priceSnapshot" BIGINT NOT NULL,
    "currencySnapshot" TEXT NOT NULL DEFAULT 'IRR',
    "sellerSnapshot" TEXT,
    "buyerSnapshot" TEXT,
    "quantity" INTEGER NOT NULL DEFAULT 1,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "commissionRate" REAL,
    "commissionAmount" BIGINT,
    "sellerAmount" BIGINT,
    "confirmedAt" DATETIME,
    "fulfilledAt" DATETIME,
    "completedAt" DATETIME,
    "cancelledAt" DATETIME,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Order_dealId_fkey" FOREIGN KEY ("dealId") REFERENCES "Deal" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "Order_dealId_key" ON "Order"("dealId");
CREATE UNIQUE INDEX "Order_orderNumber_key" ON "Order"("orderNumber");
CREATE INDEX "Order_status_idx" ON "Order"("status");

-- Part
CREATE TABLE "Part" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "productId" TEXT,
    "partNumber" TEXT,
    "oemNumber" TEXT,
    "condition" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Part_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX "Part_productId_idx" ON "Part"("productId");

-- Payment
CREATE TABLE "Payment" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "subscriptionId" TEXT,
    "orderId" TEXT,
    "amount" BIGINT NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'IRR',
    "type" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "gateway" TEXT,
    "providerReference" TEXT,
    "trackingCode" TEXT,
    "idempotencyKey" TEXT,
    "paidAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Payment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Payment_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "Payment_idempotencyKey_key" ON "Payment"("idempotencyKey");
CREATE INDEX "Payment_orderId_idx" ON "Payment"("orderId");
CREATE INDEX "Payment_status_idx" ON "Payment"("status");
CREATE INDEX "Payment_userId_idx" ON "Payment"("userId");

-- PriceEstimate
CREATE TABLE "PriceEstimate" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "listingId" TEXT,
    "estimatedPrice" REAL NOT NULL,
    "priceLower" REAL NOT NULL,
    "priceUpper" REAL NOT NULL,
    "confidence" TEXT NOT NULL DEFAULT 'MEDIUM',
    "comparableCount" INTEGER NOT NULL DEFAULT 0,
    "dataFreshness" TEXT,
    "mainDrivers" TEXT,
    "warnings" TEXT,
    "modelVersion" TEXT NOT NULL DEFAULT 'v1.0',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PriceEstimate_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "Listing" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX "PriceEstimate_listingId_idx" ON "PriceEstimate"("listingId");

-- PriceObservation
CREATE TABLE "PriceObservation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "listingId" TEXT,
    "productId" TEXT,
    "brandId" TEXT,
    "categoryId" TEXT,
    "modelId" TEXT,
    "askingPrice" BIGINT,
    "estimatedPrice" REAL,
    "priceLower" REAL,
    "priceUpper" REAL,
    "currency" TEXT NOT NULL DEFAULT 'IRR',
    "normalizedPrice" REAL,
    "source" TEXT NOT NULL DEFAULT 'LISTING',
    "sourceType" TEXT,
    "observedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "market" TEXT,
    "quality" TEXT NOT NULL DEFAULT 'MEDIUM',
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "confidence" TEXT,
    "comparableCount" INTEGER,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PriceObservation_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "Listing" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "PriceObservation_brandId_fkey" FOREIGN KEY ("brandId") REFERENCES "Brand" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "PriceObservation_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX "PriceObservation_brandId_categoryId_idx" ON "PriceObservation"("brandId", "categoryId");
CREATE INDEX "PriceObservation_modelId_idx" ON "PriceObservation"("modelId");
CREATE INDEX "PriceObservation_observedAt_idx" ON "PriceObservation"("observedAt");

-- PriceOverride
CREATE TABLE "PriceOverride" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "listingId" TEXT NOT NULL,
    "originalEstimate" REAL NOT NULL,
    "overridePrice" REAL NOT NULL,
    "reason" TEXT NOT NULL,
    "overriddenBy" TEXT,
    "overriddenAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PriceOverride_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "Listing" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "PriceOverride_listingId_idx" ON "PriceOverride"("listingId");

-- Product
CREATE TABLE "Product" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "categoryId" TEXT NOT NULL,
    "brandId" TEXT,
    "modelId" TEXT,
    "canonicalName" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "description" TEXT,
    "source" TEXT,
    "confidence" REAL,
    "verifiedAt" DATETIME,
    "verifiedBy" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Product_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Product_brandId_fkey" FOREIGN KEY ("brandId") REFERENCES "Brand" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Product_modelId_fkey" FOREIGN KEY ("modelId") REFERENCES "ProductModel" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX "Product_brandId_idx" ON "Product"("brandId");
CREATE INDEX "Product_categoryId_idx" ON "Product"("categoryId");
CREATE UNIQUE INDEX "Product_slug_key" ON "Product"("slug");

-- Review
CREATE TABLE "Review" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "authorId" TEXT NOT NULL,
    "companyId" TEXT,
    "sellerId" TEXT,
    "dealRoomId" TEXT,
    "dealId" TEXT,
    "orderId" TEXT,
    "listingId" TEXT,
    "rating" INTEGER NOT NULL,
    "title" TEXT,
    "body" TEXT NOT NULL,
    "verifiedDeal" BOOLEAN NOT NULL DEFAULT false,
    "sellerResponse" TEXT,
    "sellerRespondedAt" DATETIME,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "adminNotes" TEXT,
    "moderatedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Review_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Review_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Review_sellerId_fkey" FOREIGN KEY ("sellerId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Review_dealRoomId_fkey" FOREIGN KEY ("dealRoomId") REFERENCES "DealRoom" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Review_dealId_fkey" FOREIGN KEY ("dealId") REFERENCES "Deal" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Review_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "Listing" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX "Review_companyId_status_idx" ON "Review"("companyId", "status");
CREATE UNIQUE INDEX "Review_dealId_key" ON "Review"("dealId");
CREATE UNIQUE INDEX "Review_dealRoomId_key" ON "Review"("dealRoomId");
CREATE INDEX "Review_sellerId_status_idx" ON "Review"("sellerId", "status");
CREATE INDEX "Review_status_idx" ON "Review"("status");

-- SearchQuery
CREATE TABLE "SearchQuery" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "query" TEXT NOT NULL,
    "normalizedQuery" TEXT NOT NULL,
    "resultCount" INTEGER NOT NULL DEFAULT 0,
    "userId" TEXT,
    "ip" TEXT,
    "categorySlug" TEXT,
    "brandSlug" TEXT,
    "hasResults" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "SearchQuery_createdAt_idx" ON "SearchQuery"("createdAt");
CREATE INDEX "SearchQuery_hasResults_idx" ON "SearchQuery"("hasResults");
CREATE INDEX "SearchQuery_normalizedQuery_idx" ON "SearchQuery"("normalizedQuery");

-- SellIn7DaysApplication
CREATE TABLE "SellIn7DaysApplication" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "trackingCode" TEXT NOT NULL,
    "sellerName" TEXT NOT NULL,
    "sellerMobile" TEXT NOT NULL,
    "sellerEmail" TEXT,
    "deviceName" TEXT NOT NULL,
    "categoryId" TEXT,
    "brandId" TEXT,
    "modelName" TEXT,
    "year" INTEGER,
    "workingHours" INTEGER,
    "condition" TEXT,
    "province" TEXT,
    "city" TEXT,
    "expectedPrice" BIGINT,
    "description" TEXT,
    "prepaymentPaid" BOOLEAN NOT NULL DEFAULT false,
    "prepaymentAmount" BIGINT,
    "status" TEXT NOT NULL DEFAULT 'PENDING_PREPAYMENT',
    "currentStep" INTEGER NOT NULL DEFAULT 1,
    "inspectionDate" DATETIME,
    "valuationPrice" BIGINT,
    "salePrice" BIGINT,
    "commissionAmount" BIGINT,
    "soldAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
CREATE INDEX "SellIn7DaysApplication_sellerMobile_idx" ON "SellIn7DaysApplication"("sellerMobile");
CREATE INDEX "SellIn7DaysApplication_status_idx" ON "SellIn7DaysApplication"("status");
CREATE UNIQUE INDEX "SellIn7DaysApplication_trackingCode_key" ON "SellIn7DaysApplication"("trackingCode");

-- Service
CREATE TABLE "Service" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "key" TEXT NOT NULL,
    "nameFa" TEXT NOT NULL,
    "nameEn" TEXT,
    "description" TEXT,
    "icon" TEXT,
    "imageUrl" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "featured" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
CREATE UNIQUE INDEX "Service_key_key" ON "Service"("key");

-- SiteStat
CREATE TABLE "SiteStat" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "key" TEXT NOT NULL,
    "labelFa" TEXT NOT NULL,
    "labelEn" TEXT,
    "metric" TEXT NOT NULL,
    "customValue" TEXT,
    "icon" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
CREATE UNIQUE INDEX "SiteStat_key_key" ON "SiteStat"("key");

-- SocialReel
CREATE TABLE "SocialReel" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "listingId" TEXT NOT NULL,
    "platform" TEXT NOT NULL,
    "videoUrl" TEXT,
    "thumbnailUrl" TEXT,
    "duration" INTEGER NOT NULL DEFAULT 5,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "prompt" TEXT,
    "taskId" TEXT,
    "caption" TEXT,
    "hashtags" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "SocialReel_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "Listing" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "SocialReel_listingId_idx" ON "SocialReel"("listingId");
CREATE INDEX "SocialReel_platform_idx" ON "SocialReel"("platform");
CREATE INDEX "SocialReel_status_idx" ON "SocialReel"("status");

-- SubscriptionPlan
CREATE TABLE "SubscriptionPlan" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "code" TEXT NOT NULL,
    "nameFa" TEXT NOT NULL,
    "nameEn" TEXT,
    "description" TEXT,
    "priceMonthly" BIGINT NOT NULL DEFAULT 0,
    "priceYearly" BIGINT,
    "currency" TEXT NOT NULL DEFAULT 'IRR',
    "featuredCredits" INTEGER NOT NULL DEFAULT 0,
    "analyticsAccess" BOOLEAN NOT NULL DEFAULT false,
    "aiAssistantAccess" BOOLEAN NOT NULL DEFAULT false,
    "priorityLeads" BOOLEAN NOT NULL DEFAULT false,
    "companyPage" BOOLEAN NOT NULL DEFAULT false,
    "maxListings" INTEGER NOT NULL DEFAULT 0,
    "maxImages" INTEGER NOT NULL DEFAULT 8,
    "verifiedBadge" BOOLEAN NOT NULL DEFAULT false,
    "supportLevel" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "popular" BOOLEAN NOT NULL DEFAULT false,
    "featuresJson" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
CREATE UNIQUE INDEX "SubscriptionPlan_code_key" ON "SubscriptionPlan"("code");

-- TransportRequest
CREATE TABLE "TransportRequest" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "listingId" TEXT,
    "dealRoomId" TEXT,
    "origin" TEXT NOT NULL,
    "destination" TEXT NOT NULL,
    "cargoType" TEXT,
    "cargoWeight" REAL,
    "cargoLength" REAL,
    "cargoWidth" REAL,
    "cargoHeight" REAL,
    "vehicleType" TEXT,
    "loadingDate" DATETIME,
    "deliveryDate" DATETIME,
    "status" TEXT NOT NULL DEFAULT 'REQUESTED',
    "quotedPrice" BIGINT,
    "carrierName" TEXT,
    "carrierPhone" TEXT,
    "trackingCode" TEXT,
    "notes" TEXT,
    "requestedBy" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "TransportRequest_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "Listing" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX "TransportRequest_status_idx" ON "TransportRequest"("status");

-- UserRecommendation
CREATE TABLE "UserRecommendation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "listingId" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "score" REAL NOT NULL DEFAULT 0,
    "dismissed" BOOLEAN NOT NULL DEFAULT false,
    "clickedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "UserRecommendation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "UserRecommendation_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "Listing" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "UserRecommendation_userId_createdAt_idx" ON "UserRecommendation"("userId", "createdAt");
CREATE INDEX "UserRecommendation_userId_dismissed_idx" ON "UserRecommendation"("userId", "dismissed");
CREATE UNIQUE INDEX "UserRecommendation_userId_listingId_reason_key" ON "UserRecommendation"("userId", "listingId", "reason");

-- ═══ Category B: 5 divergent tables (additive ALTER ADD COLUMN) ═══
-- Company: 2 new columns
ALTER TABLE "Company" ADD COLUMN "avgRating" REAL;
ALTER TABLE "Company" ADD COLUMN "reviewCount" INTEGER DEFAULT 0;

-- DealRoom: 2 new columns
ALTER TABLE "DealRoom" ADD COLUMN "buyerConfirmed" BOOLEAN DEFAULT false;
ALTER TABLE "DealRoom" ADD COLUMN "sellerConfirmed" BOOLEAN DEFAULT false;

-- Listing: 13 new columns
ALTER TABLE "Listing" ADD COLUMN "rentalPeriod" TEXT;
ALTER TABLE "Listing" ADD COLUMN "deposit" BIGINT;
ALTER TABLE "Listing" ADD COLUMN "minimumRentalPeriod" INTEGER;
ALTER TABLE "Listing" ADD COLUMN "operatorIncluded" BOOLEAN DEFAULT false;
ALTER TABLE "Listing" ADD COLUMN "fuelIncluded" BOOLEAN DEFAULT false;
ALTER TABLE "Listing" ADD COLUMN "transportIncluded" BOOLEAN DEFAULT false;
ALTER TABLE "Listing" ADD COLUMN "availabilityStart" DATETIME;
ALTER TABLE "Listing" ADD COLUMN "availabilityEnd" DATETIME;
ALTER TABLE "Listing" ADD COLUMN "productId" TEXT;
ALTER TABLE "Listing" ADD COLUMN "transactionTypeId" TEXT;
ALTER TABLE "Listing" ADD COLUMN "countryId" TEXT;
ALTER TABLE "Listing" ADD COLUMN "provinceId" TEXT;
ALTER TABLE "Listing" ADD COLUMN "cityId" TEXT;

-- SiteSettings: 22 new columns
ALTER TABLE "SiteSettings" ADD COLUMN "logoHeight" INTEGER DEFAULT 80;
ALTER TABLE "SiteSettings" ADD COLUMN "footerLogoHeight" INTEGER DEFAULT 48;
ALTER TABLE "SiteSettings" ADD COLUMN "showPersianName" BOOLEAN DEFAULT true;
ALTER TABLE "SiteSettings" ADD COLUMN "logoPosition" TEXT DEFAULT 'right';
ALTER TABLE "SiteSettings" ADD COLUMN "footerLogoPosition" TEXT DEFAULT 'center';
ALTER TABLE "SiteSettings" ADD COLUMN "footerHeavixLogoUrl" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN "footerMekanixLogoUrl" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN "footerAriaLogoUrl" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN "sellIn7DaysPrepaymentAmount" BIGINT;
ALTER TABLE "SiteSettings" ADD COLUMN "sellIn7DaysCommissionRate" REAL;
ALTER TABLE "SiteSettings" ADD COLUMN "verifiedSectionTitle" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN "verifiedSectionSubtitle" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN "verifiedSectionLimit" INTEGER;
ALTER TABLE "SiteSettings" ADD COLUMN "verifiedSectionAnimation" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN "verifiedSectionVerifiedOnly" BOOLEAN;
ALTER TABLE "SiteSettings" ADD COLUMN "trustedBrandsTitle" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN "trustedBrandsSubtitle" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN "trustedBrandsDescription" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN "trustedBrandsLimit" INTEGER;
ALTER TABLE "SiteSettings" ADD COLUMN "trustedBrandsTickerSpeed" INTEGER;
ALTER TABLE "SiteSettings" ADD COLUMN "logoAnimationDurationMs" INTEGER DEFAULT 10000;
ALTER TABLE "SiteSettings" ADD COLUMN "compareVisibleAttributeIds" TEXT;

-- User: 2 new columns
ALTER TABLE "User" ADD COLUMN "avgRating" REAL;
ALTER TABLE "User" ADD COLUMN "reviewCount" INTEGER DEFAULT 0;

-- ═══ Category C: HeroConfig (additive ALTER ADD COLUMN) ═══
ALTER TABLE "HeroConfig" ADD COLUMN "cardServicesListingId" TEXT;
ALTER TABLE "HeroConfig" ADD COLUMN "cardFeaturedListingId" TEXT;
ALTER TABLE "HeroConfig" ADD COLUMN "cardExclusiveListingId" TEXT;

-- ═══ Correction: 2 missing indexes (Directive 49.2A STEP 7) ═══
-- Purely additive (CREATE INDEX, no DROP, no data impact).

CREATE INDEX "AIGatewayLog_userId_taskType_createdAt_idx" ON "AIGatewayLog"("userId", "taskType", "createdAt");

CREATE INDEX "Brand_name_idx" ON "Brand"("name");
