/**
 * HEAVIX — STEP 14.7-H: Legacy Admin Migration Checklist
 *
 * Catalogs every legacy admin page (104 routes) with metadata required
 * to decide whether the page should be:
 *   - MIGRATED to the universal resource manager at /admin/resources/[resource]
 *   - KEPT AS-IS (dashboard, settings, one-off tools)
 *   - DEPRECATED (no longer needed)
 *   - REWRITTEN (custom UI beyond what the resource manager offers)
 *
 * Each entry records:
 *   legacyPath      — the existing route under /admin/...
 *   resource        — registered AdminResource key (or null if N/A)
 *   replacementPath — where the user should go instead (or null if pending)
 *   capabilities    — CRUD verbs the original page provides
 *   migrationStatus — MIGRATED | IN_PROGRESS | PENDING | DEPRECATED | KEEP_AS_IS
 *   risk            — LOW (read-only) | MEDIUM (form write) | HIGH (state mutation / money / auth)
 *   owner           — team / ticket reference
 *
 * Usage:
 *   import { LEGACY_MIGRATION_CHECKLIST, migrationStats } from '@/lib/admin/legacy-migration-checklist';
 *
 * V2.4 — Generated by STEP 14.7-H.
 */

export type MigrationStatus = 'MIGRATED' | 'IN_PROGRESS' | 'PENDING' | 'DEPRECATED' | 'KEEP_AS_IS';
export type Risk = 'LOW' | 'MEDIUM' | 'HIGH';
export type Capability = 'list' | 'view' | 'create' | 'edit' | 'delete' | 'actions' | 'bulk' | 'export';

export interface LegacyPageEntry {
  /** Admin route path (without /admin prefix) */
  legacyPath: string;
  /** Registered resource key, or null if not resource-driven */
  resource: string | null;
  /** Where the user is redirected (or null if migration not started) */
  replacementPath: string | null;
  /** CRUD capabilities the legacy page provided */
  capabilities: Capability[];
  /** Current migration state */
  migrationStatus: MigrationStatus;
  /** Risk of leaving this page untouched */
  risk: Risk;
  /** Owner team or ticket reference */
  owner: string;
  /** Optional notes */
  notes?: string;
}

// ────────────────────────────────────────────────────────────────
// CHECKLIST — 104 legacy admin pages
// ────────────────────────────────────────────────────────────────
export const LEGACY_MIGRATION_CHECKLIST: LegacyPageEntry[] = [
  // ── 1. Dashboard & shell (KEEP_AS_IS — bespoke UI) ──────────
  { legacyPath: 'dashboard', resource: null, replacementPath: 'dashboard', capabilities: ['view'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'core', notes: 'Bespoke KPI dashboard, not a resource list' },
  { legacyPath: 'page.tsx', resource: null, replacementPath: 'dashboard', capabilities: ['view'], migrationStatus: 'DEPRECATED', risk: 'LOW', owner: 'core', notes: 'Duplicate of dashboard' },

  // ── 2. Universal Resource Manager (the migration target) ──
  { legacyPath: 'resources/[resource]', resource: null, replacementPath: 'resources/[resource]', capabilities: ['list','view','create','edit','delete','actions','bulk','export'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'core', notes: 'The migration target itself' },
  { legacyPath: 'resources/[resource]/[id]', resource: null, replacementPath: 'resources/[resource]/[id]', capabilities: ['view','edit'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'core' },
  { legacyPath: 'resources/[resource]/new', resource: null, replacementPath: 'resources/[resource]/new', capabilities: ['create'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'core' },

  // ── 3. Marketplace resources (MIGRATED — 18 registered) ────
  { legacyPath: 'listings', resource: 'listing', replacementPath: 'resources/listing', capabilities: ['list','view','create','edit','delete','actions','bulk','export'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'core' },
  { legacyPath: 'listings/[id]/edit', resource: 'listing', replacementPath: 'resources/listing/[id]', capabilities: ['edit'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'core' },
  { legacyPath: 'brands', resource: 'brand', replacementPath: 'resources/brand', capabilities: ['list','view','create','edit','delete','actions','bulk','export'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'core' },
  { legacyPath: 'brands/new', resource: 'brand', replacementPath: 'resources/brand/new', capabilities: ['create'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'core' },
  { legacyPath: 'users', resource: 'user', replacementPath: 'resources/user', capabilities: ['list','view','create','edit','delete','actions','bulk','export'], migrationStatus: 'MIGRATED', risk: 'HIGH', owner: 'core', notes: 'Risk HIGH due to user role/grants' },
  { legacyPath: 'users/[id]', resource: 'user', replacementPath: 'resources/user/[id]', capabilities: ['view','edit'], migrationStatus: 'MIGRATED', risk: 'HIGH', owner: 'core' },

  // ── 4. Store resources (MIGRATED) ───────────────────────────
  { legacyPath: 'store', resource: null, replacementPath: 'store', capabilities: ['view'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'store', notes: 'Store landing hub' },
  { legacyPath: 'products', resource: 'product', replacementPath: 'resources/product', capabilities: ['list','view','create','edit','delete','actions','bulk','export'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'store' },
  { legacyPath: 'products/[id]/edit', resource: 'product', replacementPath: 'resources/product/[id]', capabilities: ['edit'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'store' },
  { legacyPath: 'store/parts', resource: 'part', replacementPath: 'resources/part', capabilities: ['list','view','create','edit','delete','bulk','export'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'store' },
  { legacyPath: 'store/orders', resource: 'order', replacementPath: 'resources/order', capabilities: ['list','view','edit','actions','bulk','export'], migrationStatus: 'MIGRATED', risk: 'HIGH', owner: 'store', notes: 'Order state mutations affect ledger' },
  { legacyPath: 'store/payments', resource: 'payment', replacementPath: 'resources/payment', capabilities: ['list','view','actions','export'], migrationStatus: 'MIGRATED', risk: 'HIGH', owner: 'store', notes: 'Money flow — keep tight RBAC' },
  { legacyPath: 'store/customers', resource: 'user', replacementPath: 'resources/user?filter=userType=BUYER', capabilities: ['list','view','edit'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'store' },
  { legacyPath: 'store/mechanics', resource: 'user', replacementPath: 'resources/user?filter=userType=SELLER', capabilities: ['list','view','edit'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'store' },
  { legacyPath: 'store/brands', resource: 'brand', replacementPath: 'resources/brand', capabilities: ['list','view','create','edit'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'store' },
  { legacyPath: 'store/categories', resource: 'category', replacementPath: 'resources/category', capabilities: ['list','view','create','edit','delete'], migrationStatus: 'IN_PROGRESS', risk: 'MEDIUM', owner: 'store', notes: 'Awaiting category resource registration' },
  { legacyPath: 'store/car-models', resource: 'productModel', replacementPath: 'resources/productModel', capabilities: ['list','view','create','edit'], migrationStatus: 'PENDING', risk: 'MEDIUM', owner: 'store' },
  { legacyPath: 'store/currency', resource: null, replacementPath: 'settings#currency', capabilities: ['view','edit'], migrationStatus: 'PENDING', risk: 'MEDIUM', owner: 'store' },
  { legacyPath: 'store/ai-scraper', resource: null, replacementPath: 'ai-scraper', capabilities: ['view','actions'], migrationStatus: 'KEEP_AS_IS', risk: 'HIGH', owner: 'ai', notes: 'Bespoke scraper UI' },

  // ── 5. Marketplace control-plane resources (MIGRATED) ──────
  { legacyPath: 'deal-rooms', resource: 'deal', replacementPath: 'resources/deal', capabilities: ['list','view','edit','actions','export'], migrationStatus: 'MIGRATED', risk: 'HIGH', owner: 'core' },
  { legacyPath: 'rfq', resource: 'rfq', replacementPath: 'resources/rfq', capabilities: ['list','view','create','edit','actions','bulk','export'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'core' },
  { legacyPath: 'requests', resource: 'buyRequest', replacementPath: 'resources/buyRequest', capabilities: ['list','view','create','edit','delete','actions'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'core' },
  { legacyPath: 'offers', resource: 'offer', replacementPath: 'resources/offer', capabilities: ['list','view','edit','actions','export'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'core' },
  { legacyPath: 'auctions', resource: 'auction', replacementPath: 'resources/auction', capabilities: ['list','view','create','edit','actions','export'], migrationStatus: 'MIGRATED', risk: 'HIGH', owner: 'core' },
  { legacyPath: 'inspections', resource: 'inspection', replacementPath: 'resources/inspection', capabilities: ['list','view','create','edit','actions'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'core' },
  { legacyPath: 'transport', resource: 'transportRequest', replacementPath: 'resources/transportRequest', capabilities: ['list','view','create','edit','actions'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'core' },
  { legacyPath: 'rejections', resource: 'listingRejection', replacementPath: 'resources/listingRejection', capabilities: ['list','view','create','edit'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'core' },
  { legacyPath: 'reviews', resource: 'review', replacementPath: 'resources/review', capabilities: ['list','view','edit','actions','export'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'core' },

  // ── 6. Taxonomy (mix — some migrated, some pending) ────────
  { legacyPath: 'taxonomy', resource: null, replacementPath: 'taxonomy', capabilities: ['view'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'taxonomy' },
  { legacyPath: 'taxonomy/brands', resource: 'brand', replacementPath: 'resources/brand', capabilities: ['list','view','create','edit'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'taxonomy' },
  { legacyPath: 'taxonomy/brands/[id]', resource: 'brand', replacementPath: 'resources/brand/[id]', capabilities: ['view','edit'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'taxonomy' },
  { legacyPath: 'taxonomy/brands/new', resource: 'brand', replacementPath: 'resources/brand/new', capabilities: ['create'], migrationStatus: 'MIGRATED', risk: 'MEDIUM', owner: 'taxonomy' },
  { legacyPath: 'taxonomy/attributes', resource: 'attributeDefinition', replacementPath: 'resources/attributeDefinition', capabilities: ['list','view','create','edit','delete'], migrationStatus: 'PENDING', risk: 'MEDIUM', owner: 'taxonomy' },
  { legacyPath: 'taxonomy/industries', resource: 'applicationIndustry', replacementPath: 'resources/applicationIndustry', capabilities: ['list','view','create','edit'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'taxonomy' },
  { legacyPath: 'taxonomy/locations', resource: null, replacementPath: 'resources/country', capabilities: ['list','view','edit'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'taxonomy' },
  { legacyPath: 'taxonomy/services', resource: 'serviceType', replacementPath: 'resources/serviceType', capabilities: ['list','view','create','edit'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'taxonomy' },
  { legacyPath: 'taxonomy/transactions', resource: 'transactionType', replacementPath: 'resources/transactionType', capabilities: ['list','view','create','edit'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'taxonomy' },
  { legacyPath: 'categories', resource: 'category', replacementPath: 'resources/category', capabilities: ['list','view','create','edit','delete'], migrationStatus: 'IN_PROGRESS', risk: 'MEDIUM', owner: 'taxonomy' },
  { legacyPath: 'categories/new', resource: 'category', replacementPath: 'resources/category/new', capabilities: ['create'], migrationStatus: 'IN_PROGRESS', risk: 'MEDIUM', owner: 'taxonomy' },
  { legacyPath: 'brand-families', resource: 'brandFamily', replacementPath: 'resources/brandFamily', capabilities: ['list','view','create','edit','delete'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'taxonomy' },

  // ── 7. Companies & partners (PENDING) ──────────────────────
  { legacyPath: 'companies', resource: 'company', replacementPath: 'resources/company', capabilities: ['list','view','create','edit','delete','actions','bulk','export'], migrationStatus: 'MIGRATED', risk: 'HIGH', owner: 'core' },
  { legacyPath: 'companies/[id]', resource: 'company', replacementPath: 'resources/company/[id]', capabilities: ['view','edit'], migrationStatus: 'MIGRATED', risk: 'HIGH', owner: 'core' },
  { legacyPath: 'partners', resource: 'companyPartner', replacementPath: 'resources/companyPartner', capabilities: ['list','view','create','edit','delete'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'core' },

  // ── 8. Content & media (mix) ────────────────────────────────
  { legacyPath: 'articles', resource: 'article', replacementPath: 'resources/article', capabilities: ['list','view','create','edit','delete','actions','bulk'], migrationStatus: 'PENDING', risk: 'MEDIUM', owner: 'content' },
  { legacyPath: 'knowledge', resource: 'knowledgeEntry', replacementPath: 'resources/knowledgeEntry', capabilities: ['list','view','create','edit','delete'], migrationStatus: 'PENDING', risk: 'MEDIUM', owner: 'content' },
  { legacyPath: 'knowledge-graph', resource: null, replacementPath: 'knowledge-graph', capabilities: ['view'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'ai', notes: 'Bespoke graph visualizer' },
  { legacyPath: 'media', resource: 'attachment', replacementPath: 'resources/attachment', capabilities: ['list','view','delete','bulk'], migrationStatus: 'PENDING', risk: 'MEDIUM', owner: 'content' },
  { legacyPath: 'reels', resource: 'socialReel', replacementPath: 'resources/socialReel', capabilities: ['list','view','create','edit','delete','actions'], migrationStatus: 'PENDING', risk: 'MEDIUM', owner: 'content' },
  { legacyPath: 'social-reels', resource: 'socialReel', replacementPath: 'resources/socialReel', capabilities: ['list','view','edit','actions'], migrationStatus: 'DEPRECATED', risk: 'LOW', owner: 'content', notes: 'Duplicate of /reels — consolidate' },
  { legacyPath: 'courses', resource: null, replacementPath: 'courses', capabilities: ['list','view','create','edit'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'content' },
  { legacyPath: 'content-factory', resource: null, replacementPath: 'content-factory', capabilities: ['view','actions'], migrationStatus: 'KEEP_AS_IS', risk: 'HIGH', owner: 'ai', notes: 'Bespoke AI generation UI' },
  { legacyPath: 'content-decay', resource: null, replacementPath: 'content-decay', capabilities: ['view'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'content', notes: 'Analytics dashboard' },

  // ── 9. CMS / Home builder (KEEP_AS_IS — bespoke) ───────────
  { legacyPath: 'home', resource: null, replacementPath: 'home', capabilities: ['view'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'cms' },
  { legacyPath: 'home/categories', resource: null, replacementPath: 'home/categories', capabilities: ['view','edit'], migrationStatus: 'KEEP_AS_IS', risk: 'MEDIUM', owner: 'cms' },
  { legacyPath: 'home/footer', resource: null, replacementPath: 'home/footer', capabilities: ['view','edit'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'cms' },
  { legacyPath: 'home/header', resource: null, replacementPath: 'home/header', capabilities: ['view','edit'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'cms' },
  { legacyPath: 'home/hero', resource: null, replacementPath: 'home/hero', capabilities: ['view','edit'], migrationStatus: 'KEEP_AS_IS', risk: 'MEDIUM', owner: 'cms' },
  { legacyPath: 'home/trusted-brands', resource: null, replacementPath: 'home/trusted-brands', capabilities: ['view','edit'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'cms' },
  { legacyPath: 'home/verified-machines', resource: null, replacementPath: 'home/verified-machines', capabilities: ['view','edit'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'cms' },
  { legacyPath: 'homepage-layout', resource: 'adminPage', replacementPath: 'resources/adminPage', capabilities: ['list','view','create','edit','actions'], migrationStatus: 'IN_PROGRESS', risk: 'HIGH', owner: 'cms', notes: 'Page Builder integration' },
  { legacyPath: 'menu', resource: 'menuItem', replacementPath: 'resources/menuItem', capabilities: ['list','view','create','edit','delete'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'cms' },

  // ── 10. AI suite (KEEP_AS_IS — bespoke) ────────────────────
  { legacyPath: 'ai-agents', resource: 'aiAgent', replacementPath: 'resources/aiAgent', capabilities: ['list','view','create','edit','delete','actions'], migrationStatus: 'PENDING', risk: 'HIGH', owner: 'ai' },
  { legacyPath: 'ai-analyst', resource: null, replacementPath: 'ai-analyst', capabilities: ['view','actions'], migrationStatus: 'KEEP_AS_IS', risk: 'HIGH', owner: 'ai' },
  { legacyPath: 'ai-budget', resource: 'aiBudget', replacementPath: 'resources/aiBudget', capabilities: ['list','view','edit'], migrationStatus: 'PENDING', risk: 'HIGH', owner: 'ai' },
  { legacyPath: 'ai-evaluation', resource: null, replacementPath: 'ai-evaluation', capabilities: ['view'], migrationStatus: 'KEEP_AS_IS', risk: 'MEDIUM', owner: 'ai' },
  { legacyPath: 'ai-gateway', resource: 'aiGatewayLog', replacementPath: 'resources/aiGatewayLog', capabilities: ['list','view','export'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'ai' },
  { legacyPath: 'ai-scraper', resource: null, replacementPath: 'ai-scraper', capabilities: ['view','actions'], migrationStatus: 'KEEP_AS_IS', risk: 'HIGH', owner: 'ai' },

  // ── 11. Analytics & signals (KEEP_AS_IS — dashboards) ──────
  { legacyPath: 'analytics', resource: 'analyticsEvent', replacementPath: 'resources/analyticsEvent', capabilities: ['list','view','export'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'analytics' },
  { legacyPath: 'site-stats', resource: 'siteStat', replacementPath: 'resources/siteStat', capabilities: ['list','view','export'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'analytics' },
  { legacyPath: 'demand-signals', resource: 'demandSignal', replacementPath: 'resources/demandSignal', capabilities: ['list','view','export'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'analytics' },
  { legacyPath: 'demand-engine', resource: null, replacementPath: 'demand-engine', capabilities: ['view'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'analytics', notes: 'Bespoke engine view' },
  { legacyPath: 'market-intelligence', resource: null, replacementPath: 'market-intelligence', capabilities: ['view'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'analytics' },
  { legacyPath: 'market-heatmap', resource: null, replacementPath: 'market-heatmap', capabilities: ['view'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'analytics' },
  { legacyPath: 'hot-searches', resource: 'hotSearch', replacementPath: 'resources/hotSearch', capabilities: ['list','view','edit','delete'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'analytics' },
  { legacyPath: 'opportunities', resource: 'opportunity', replacementPath: 'resources/opportunity', capabilities: ['list','view','edit','actions'], migrationStatus: 'PENDING', risk: 'MEDIUM', owner: 'analytics' },
  { legacyPath: 'opportunity-radar', resource: null, replacementPath: 'opportunity-radar', capabilities: ['view'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'analytics' },
  { legacyPath: 'growth-engine', resource: null, replacementPath: 'growth-engine', capabilities: ['view','actions'], migrationStatus: 'KEEP_AS_IS', risk: 'MEDIUM', owner: 'analytics' },
  { legacyPath: 'compare', resource: 'comparisonSession', replacementPath: 'resources/comparisonSession', capabilities: ['list','view','delete'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'analytics' },
  { legacyPath: 'compatibility', resource: 'compatibilityEdge', replacementPath: 'resources/compatibilityEdge', capabilities: ['list','view','create','edit','delete'], migrationStatus: 'PENDING', risk: 'MEDIUM', owner: 'analytics' },

  // ── 12. Pricing intelligence ────────────────────────────────
  { legacyPath: 'price-intelligence', resource: null, replacementPath: 'price-intelligence', capabilities: ['view'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'pricing' },
  { legacyPath: 'pricing', resource: 'subscriptionPlan', replacementPath: 'resources/subscriptionPlan', capabilities: ['list','view','create','edit'], migrationStatus: 'PENDING', risk: 'MEDIUM', owner: 'pricing' },
  { legacyPath: 'subscriptions', resource: 'premiumSubscription', replacementPath: 'resources/premiumSubscription', capabilities: ['list','view','edit','actions','export'], migrationStatus: 'PENDING', risk: 'HIGH', owner: 'pricing' },

  // ── 13. Catalog & verification ─────────────────────────────
  { legacyPath: 'catalog-health', resource: null, replacementPath: 'catalog-health', capabilities: ['view','actions'], migrationStatus: 'KEEP_AS_IS', risk: 'MEDIUM', owner: 'core' },
  { legacyPath: 'lifecycle', resource: null, replacementPath: 'lifecycle', capabilities: ['view'], migrationStatus: 'KEEP_AS_IS', risk: 'LOW', owner: 'core' },

  // ── 14. Moderation & audit ─────────────────────────────────
  { legacyPath: 'moderation', resource: 'moderationLog', replacementPath: 'resources/moderationLog', capabilities: ['list','view','actions','export'], migrationStatus: 'PENDING', risk: 'HIGH', owner: 'trust' },
  { legacyPath: 'audit-log', resource: 'auditLog', replacementPath: 'resources/auditLog', capabilities: ['list','view','export'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'trust', notes: 'Read-only audit trail' },

  // ── 15. Dictionary & taxonomy extras ───────────────────────
  { legacyPath: 'dictionary', resource: 'industrialTerm', replacementPath: 'resources/industrialTerm', capabilities: ['list','view','create','edit','delete'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'taxonomy' },

  // ── 16. System & settings (KEEP_AS_IS — bespoke) ───────────
  { legacyPath: 'settings', resource: null, replacementPath: 'settings', capabilities: ['view','edit'], migrationStatus: 'KEEP_AS_IS', risk: 'HIGH', owner: 'core' },
  { legacyPath: 'feature-flags', resource: 'featureFlag', replacementPath: 'resources/featureFlag', capabilities: ['list','view','create','edit','delete','actions'], migrationStatus: 'PENDING', risk: 'HIGH', owner: 'core' },
  { legacyPath: 'api-keys', resource: null, replacementPath: 'api-keys', capabilities: ['list','create','delete'], migrationStatus: 'KEEP_AS_IS', risk: 'HIGH', owner: 'core' },
  { legacyPath: 'webhooks', resource: null, replacementPath: 'webhooks', capabilities: ['list','view','create','edit','delete'], migrationStatus: 'PENDING', risk: 'HIGH', owner: 'core' },
  { legacyPath: 'automations', resource: null, replacementPath: 'automations', capabilities: ['list','view','create','edit','delete'], migrationStatus: 'PENDING', risk: 'HIGH', owner: 'core' },
  { legacyPath: 'jobs', resource: null, replacementPath: 'jobs', capabilities: ['list','view','actions'], migrationStatus: 'KEEP_AS_IS', risk: 'MEDIUM', owner: 'core' },
  { legacyPath: 'launch-phases', resource: 'launchPhase', replacementPath: 'resources/launchPhase', capabilities: ['list','view','edit','actions'], migrationStatus: 'PENDING', risk: 'MEDIUM', owner: 'core' },
  { legacyPath: 'policies', resource: null, replacementPath: 'policies', capabilities: ['list','view','create','edit','delete'], migrationStatus: 'PENDING', risk: 'HIGH', owner: 'core' },

  // ── 17. SEO ────────────────────────────────────────────────
  { legacyPath: 'seo', resource: 'seoMetadata', replacementPath: 'resources/seoMetadata', capabilities: ['list','view','edit','export'], migrationStatus: 'PENDING', risk: 'LOW', owner: 'seo' },

  // ── 18. Services & procurement ──────────────────────────────
  { legacyPath: 'services', resource: 'service', replacementPath: 'resources/service', capabilities: ['list','view','create','edit','delete','actions'], migrationStatus: 'PENDING', risk: 'MEDIUM', owner: 'core' },
  { legacyPath: 'procurement', resource: null, replacementPath: 'procurement', capabilities: ['view','actions'], migrationStatus: 'KEEP_AS_IS', risk: 'MEDIUM', owner: 'core' },
  { legacyPath: 'sell-in-7-days', resource: 'sellIn7DaysApplication', replacementPath: 'resources/sellIn7DaysApplication', capabilities: ['list','view','edit','actions'], migrationStatus: 'PENDING', risk: 'MEDIUM', owner: 'growth' },
];

// ────────────────────────────────────────────────────────────────
// HELPERS
// ────────────────────────────────────────────────────────────────
export function migrationStats() {
  const total = LEGACY_MIGRATION_CHECKLIST.length;
  const byStatus = {
    MIGRATED: LEGACY_MIGRATION_CHECKLIST.filter(p => p.migrationStatus === 'MIGRATED').length,
    IN_PROGRESS: LEGACY_MIGRATION_CHECKLIST.filter(p => p.migrationStatus === 'IN_PROGRESS').length,
    PENDING: LEGACY_MIGRATION_CHECKLIST.filter(p => p.migrationStatus === 'PENDING').length,
    DEPRECATED: LEGACY_MIGRATION_CHECKLIST.filter(p => p.migrationStatus === 'DEPRECATED').length,
    KEEP_AS_IS: LEGACY_MIGRATION_CHECKLIST.filter(p => p.migrationStatus === 'KEEP_AS_IS').length,
  };
  const byRisk = {
    LOW: LEGACY_MIGRATION_CHECKLIST.filter(p => p.risk === 'LOW').length,
    MEDIUM: LEGACY_MIGRATION_CHECKLIST.filter(p => p.risk === 'MEDIUM').length,
    HIGH: LEGACY_MIGRATION_CHECKLIST.filter(p => p.risk === 'HIGH').length,
  };
  const byOwner: Record<string, number> = {};
  for (const e of LEGACY_MIGRATION_CHECKLIST) byOwner[e.owner] = (byOwner[e.owner] || 0) + 1;
  return {
    total,
    byStatus,
    byRisk,
    byOwner,
    // Migration progress: MIGRATED + KEEP_AS_IS count as "addressed"
    addressed: byStatus.MIGRATED + byStatus.KEEP_AS_IS + byStatus.DEPRECATED,
    pending: byStatus.IN_PROGRESS + byStatus.PENDING,
    progressPct: Math.round(((byStatus.MIGRATED + byStatus.KEEP_AS_IS + byStatus.DEPRECATED) / total) * 100),
  };
}

export function getEntryByPath(legacyPath: string): LegacyPageEntry | undefined {
  return LEGACY_MIGRATION_CHECKLIST.find(e => e.legacyPath === legacyPath);
}

export function getEntriesByStatus(status: MigrationStatus): LegacyPageEntry[] {
  return LEGACY_MIGRATION_CHECKLIST.filter(e => e.migrationStatus === status);
}

export function getEntriesByOwner(owner: string): LegacyPageEntry[] {
  return LEGACY_MIGRATION_CHECKLIST.filter(e => e.owner === owner);
}
